services:
  backend:
    build:
      context: .
      target: backend
    ports:
      - "2000:2000"
    volumes:
      - ./backend:/app/packages/backend
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  frontend:
    build:
      context: .
      target: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/packages/frontend
    environment:
      - NODE_ENV=development

  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=twinkle
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
