services:
  backend:
    build:
      context: .
      target: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app/packages/backend
    depends_on:
      - db

  frontend:
    build:
      context: .
      target: frontend
    ports:
      - "80:3000"
    volumes:
      - ./frontend:/app/packages/frontend

  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
