version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=twinkle
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080