version: '3.8'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=twinkle
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234

  frontend:
    restart: unless-stopped
    image: twinkle_frontend
    init: true
    expose:
      - 3000
    ports:
      - '3000:3000'
    build:
      context: packages/frontend/Dockerfile
      args:
        CI: ${CI}
    extra_hosts:
      - host.docker.internal:host-gateway
