services:
  backend:
    build:
      context: .
      target: backend
    env_file: "packages/backend/.env"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app/packages/backend
    depends_on:
      - db

  frontend:
    build:
      context: .
      target: frontend
    env_file: "packages/frontend/.env"
    ports:
      - "80:3000"
    volumes:
      - ./frontend:/app/packages/frontend

  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: ".env"
