services:
  backend:
    build:
      context: .
      target: backend
    env_file: "packages/backend/.env"
    ports:
      - "3000:2000"
    volumes:
      - ./backend:/app/packages/backend
    depends_on:
      - db

  frontend:
    build:
      context: .
      target: frontend
    env_file: "packages/frontend/.env"
    ports:
      - "80:3000"
    volumes:
      - ./frontend:/app/packages/frontend

  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=twinkle
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
